export const staticRaffleItems = [
  {
    id: 101,
    name: "Hoodie (black)",
    img: require("@static/raffle/items/UW_hoodie.png"),
    rafflePartner: "Waterloo University",
    partnerLogo: require("@static/error-logo.png"),
    availability: 3,
    description: `This comfortable and colourful  tee will not only be fun to wear but will also raise awareness of projects to help endangered frogs. There are lots of designs to choose from (check here: https://savethefrogs.com/shop/#shirts) Every shirt  comes with an image on the front and the name and website on the back. Choose the design that suits you! `,
    resourceLink: "https://building-u.com/programs/concept-pre-entrepreneur-program/",
  },
  {
    id: 102,
    name: "T-Shirt",
    img: require("@static/error-logo.png"),
    rafflePartner: "SavetheFrogs!",
    partnerLogo: require("@static/error-logo.png"),
    availability: 1,
    description: `This comfortable and colourful  tee will not only be fun to wear but will also raise awareness of projects to help endangered frogs. There are lots of designs to choose from (check here: https://savethefrogs.com/shop/#shirts) Every shirt  comes with an image on the front and the name and website on the back. Choose the design that suits you! `,
    resourceLink: "https://building-u.com/funding/save-the-frogs-art-contest/",
  },
  {
    id: 103,
    name: "Shoulder Sling",
    img: require("@static/raffle/items/ORGANICCOTTONU-SACU-Do-U(Black&White).png"),
    rafflePartner: "building-U",
    partnerLogo: require("@static/raffle/partners/building-U.png"),
    availability: 3,
    description: `Headed to class, to the market, to the beach, or nowhere particular,, our lightweight and sturdy shoulder sling let's you take all you need from home for your travels... Or collect all you want from your travels to take home.`,
    resourceLink: "https://building-u.com/opportunities/zooniverse/",
  },
];
